from __future__ import annotations

import csv
from pathlib import Path
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1] / "outputs"
DATA_DIR = ROOT / "data"
RETRIEVED_AT_UTC = "2026-07-22T10:45:00+00:00"
PROVIDER = "web_recherche_elargie_v1"

SUMMARY_FIELDS = [
    "site_uid",
    "supplier",
    "roles",
    "country_code",
    "location",
    "lat",
    "lon",
    "query",
    "provider",
    "context_search_status",
    "retrieved_at_utc",
    "result_count",
    "source_count",
    "top_title",
    "top_url",
    "top_domain",
    "weak_signal_score",
    "weak_signal_categories",
    "weak_signal_hits",
    "documentary_criticality_score",
    "aerospace_relevance_score",
    "official_source_candidate",
    "data_confidence_score",
    "context_short_summary",
]

RESULT_FIELDS = [
    "site_uid",
    "supplier",
    "roles",
    "country_code",
    "location",
    "lat",
    "lon",
    "query",
    "provider",
    "search_status",
    "retrieved_at_utc",
    "result_rank",
    "title",
    "url",
    "domain",
    "description",
    "signal_categories",
    "signal_hits",
    "weak_signal_score",
    "aerospace_relevance_score",
    "official_source_candidate",
]


def domain(url: str) -> str:
    return urlparse(url).netloc.replace("www.", "")


def result(
    title: str,
    url: str,
    description: str,
    *,
    categories: str = "",
    hits: str = "",
    weak: float = 0.0,
    aero: float = 0.0,
    official: int = 0,
) -> dict[str, object]:
    return {
        "title": title,
        "url": url,
        "description": description,
        "signal_categories": categories,
        "signal_hits": hits,
        "weak_signal_score": weak,
        "aerospace_relevance_score": aero,
        "official_source_candidate": official,
    }


ENTRIES = [
    {
        "site_uid": "safran_seats_safran_internal_group@@safran_seats_safran_internal_group@48.8125,1.9495",
        "supplier": "Safran Seats / Safran internal group",
        "query": "Safran Seats aircraft seats supplier France official",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.12,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.94,
        "summary": "Specialite confirmee : Safran Seats est un acteur majeur des sieges passagers, equipage et helicopteres ; noeud OEM central du cas siege aeronautique.",
        "results": [
            result("Safran Seats - A global key player in passenger and technical aircraft seats", "https://www.safran-group.com/companies/safran-seats", "Source officielle : Safran Seats est presente comme un des leaders mondiaux du siege passager et technique.", aero=1.0, official=1),
            result("Safran - Aircraft interiors", "https://www.safran-group.com/", "Source officielle groupe : Safran couvre des produits d'interieurs cabine incluant sieges et systemes de cabine.", aero=0.9, official=1),
        ],
    },
    {
        "site_uid": "amag_austria_metall@@amag_austria_metall@48.2267,13.0357",
        "supplier": "AMAG Austria Metall",
        "query": "AMAG Austria Metall aerospace supplier supply chain",
        "weak": 0.24,
        "cats": "dependance_source_unique",
        "hits": "dependance_source_unique:single source",
        "doc": 0.29,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.95,
        "summary": "Specialite confirmee : aluminium aeronautique et chaine integree. Vigilance contexte moderee car une chaine integree peut creer une dependance industrielle.",
        "results": [
            result("Supply Chain Management - AMAG", "https://www.amag-al4u.com/en/industries/luftfahrt-und-raumfahrt/komponenten/supply-chain-management", "Source officielle : pilotage fournisseurs et reseau supply pour composants aeronautiques.", aero=1.0, official=1),
            result("Components - AMAG", "https://www.amag-al4u.com/en/amag-group/components", "Source officielle : chaine de valeur de la matiere primaire au composant pret a monter.", categories="dependance_source_unique", hits="dependance_source_unique:single source", weak=0.24, aero=1.0, official=1),
        ],
    },
    {
        "site_uid": "alcoa@@alcoa@40.4406,-79.9959",
        "supplier": "Alcoa",
        "query": "Alcoa aerospace aluminium supply disruption cyclone war",
        "weak": 0.86,
        "cats": "rupture_approvisionnement|incident_industriel|risque_geopolitique_reglementaire",
        "hits": "rupture_approvisionnement:disruption|incident_industriel:cyclone|risque_geopolitique_reglementaire:war",
        "doc": 0.79,
        "aero": 0.75,
        "official": 1,
        "confidence": 0.82,
        "summary": "Signal faible fort : perturbations alumine, cyclone et contexte geopolitique cites dans les resultats ; fournisseur matiere critique pour l'aluminium.",
        "results": [
            result("Alcoa Cuts Production Guidance, Says Alumina Prices Stable Despite Iran War", "https://www.wsj.com/business/earnings/alcoa-cuts-full-year-alumina-guidance-posts-higher-second-quarter-profit-c693eee8", "Article marche : reduction de guidance alumine apres perturbations operationnelles, contamination organique et impact cyclone.", categories="rupture_approvisionnement|incident_industriel", hits="rupture_approvisionnement:disruption|incident_industriel:cyclone", weak=0.86, aero=0.25),
            result("Alcoa - Suppliers", "https://www.alcoa.com/global/en/contact/supplier", "Source officielle : page fournisseurs et vigilance droits humains ; utile pour qualifier le cadre de risque supply.", categories="risque_geopolitique_reglementaire", hits="risque_geopolitique_reglementaire:forced labor", weak=0.28, official=1),
            result("Alcoa draws more orders after Middle East supply disruption", "https://aluminiumtoday.com/news/alcoa-draws-more-orders-after-middle-east-supply-disruption", "Article secteur : incertitude Moyen-Orient et report possible de demandes clients vers Alcoa.", categories="rupture_approvisionnement|risque_geopolitique_reglementaire", hits="rupture_approvisionnement:supply disruption|risque_geopolitique_reglementaire:conflict", weak=0.62, aero=0.1),
        ],
    },
    {
        "site_uid": "sumpar@@sumpar@49.3893,1.2086",
        "supplier": "SUMPAR",
        "query": "SUMPAR aerospace France supplier machining",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.05,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.92,
        "summary": "Specialite confirmee : pieces metalliques et sous-ensembles pour industrie aeronautique ; pas de crise publique specifique trouvee.",
        "results": [
            result("Home - Sumpar", "https://www.sumpar.com/en/", "Source officielle : pieces metalliques et sous-ensembles a forte valeur ajoutee pour l'aeronautique.", aero=1.0, official=1),
            result("Sumpar - company profile", "https://www.zoominfo.com/c/sumpar/346129552", "Profil entreprise : classification aerospace and defense manufacturing en France.", aero=0.75),
        ],
    },
    {
        "site_uid": "euralliage_ile_de_france@@euralliage_ile_de_france@48.986,2.449",
        "supplier": "Euralliage Ile de France",
        "query": "Euralliage metals distributor France aerospace",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.08,
        "aero": 0.15,
        "official": 1,
        "confidence": 0.69,
        "summary": "Specialite a confirmer : distributeur et stockiste de metaux non ferreux ; pertinence aeronautique moins explicite dans les sources publiques.",
        "results": [
            result("Euralliage - stockage negoce et decoupe des metaux non ferreux", "https://www.euralliage.com/", "Source officielle : stockage, negoce et decoupe de metaux non ferreux.", aero=0.15, official=1),
            result("EURALLIAGE - Kompass", "https://us.kompass.com/c/euralliage/fr8507906/", "Profil entreprise : commerce de gros de metaux et minerais metalliques."),
        ],
    },
    {
        "site_uid": "aluminium_corporation_of_china_chalco@@aluminium_corporation_of_china_chalco@39.9042,116.4074",
        "supplier": "Aluminium Corporation of China / Chalco",
        "query": "Chalco aluminium supply chain risk",
        "weak": 0.74,
        "cats": "risque_geopolitique_reglementaire|fragilite_financiere|rupture_approvisionnement",
        "hits": "risque_geopolitique_reglementaire:forced labor|fragilite_financiere:negative outlook|rupture_approvisionnement:geopolitical shifts",
        "doc": 0.71,
        "aero": 0.25,
        "official": 1,
        "confidence": 0.76,
        "summary": "Signal faible fort : matiere aluminium critique, exposition Chine, signaux financiers/reglementaires et risque geopolitique a suivre.",
        "results": [
            result("Chalco - official company site", "https://www.chalco.com.cn/en/", "Source officielle : producteur aluminium integre, pertinent pour matiere amont.", aero=0.25, official=1),
            result("S&P Global - China commodities pressure", "https://www.spglobal.com/ratings/en/regulatory/article/-/view/type/HTML/id/3391673", "Contexte secteur Chine : pression sur industrie lourde et dette, utile comme signal macro amont.", categories="fragilite_financiere", hits="fragilite_financiere:negative outlook", weak=0.42),
        ],
    },
    {
        "site_uid": "espace@@espace@44.7776,-0.6475",
        "supplier": "ESPACE",
        "query": "ESPACE aerospace France supplier machining",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.12,
        "aero": 0.55,
        "official": 0,
        "confidence": 0.48,
        "summary": "Specialite probable : fiche Airframer indique usinage et services industriels aeronautiques ; confiance moyenne car source secondaire.",
        "results": [
            result("ESPACE s.a.s - Airframer", "https://www.airframer.com/direct_detail.html?company=123447", "Source secondaire : usinage, fabrication et services industriels pour l'aeronautique.", aero=0.55),
        ],
    },
    {
        "site_uid": "senior_aerospace_thailand_tier1@@senior_aerospace_thailand_tier1@13.0914,101.0108",
        "supplier": "Senior Aerospace Thailand",
        "query": "Senior Aerospace Thailand aerospace supplier certification",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.09,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.86,
        "summary": "Specialite confirmee : fournisseur aeronautique en Thailande ; exposition regionale aux pluies/tempetes traitee par la simulation SDD.",
        "results": [
            result("Senior Aerospace Thailand case study", "https://gradion.com/en/case-studies/senior-aerospace", "Source secteur : filiale aeronautique avec clients OEM et exigences qualite.", aero=1.0),
        ],
    },
    {
        "site_uid": "ensinger@@ensinger@48.501,8.8202",
        "supplier": "Ensinger",
        "query": "Ensinger aircraft aerospace plastics QPL Airbus Boeing",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.10,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.91,
        "summary": "Specialite confirmee : plastiques et composants structuraux aerospace, avec qualification QPL chez Airbus/Boeing selon la source officielle.",
        "results": [
            result("Aerospace, aircraft and aviation plastic solutions - Ensinger", "https://www.ensingerplastics.com/en/aircraft-aerospace", "Source officielle : Ensinger indique etre qualifie QPL chez Airbus, Boeing et autres OEM.", aero=1.0, official=1),
            result("Aircraft structural plastic components - Ensinger", "https://www.ensingerplastics.com/en/aircraft-aerospace/plastics-aerospace-industry/aircraft-structural-components", "Source officielle : composants structuraux et semi-produits de haute qualite pour aerospace.", aero=1.0, official=1),
        ],
    },
    {
        "site_uid": "toray_industries@@toray_industries@35.6866,139.7746",
        "supplier": "Toray Industries",
        "query": "Toray carbon fiber Boeing aerospace supply agreement",
        "weak": 0.18,
        "cats": "dependance_source_unique",
        "hits": "dependance_source_unique:single source",
        "doc": 0.26,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.90,
        "summary": "Capacite confirmee : fibre carbone/prepreg aeronautique avec accords long terme Boeing et Syensqo ; criticite moderee car fournisseur strategique de composite.",
        "results": [
            result("Toray Extends Comprehensive Agreement with Boeing", "https://www.toraycma.com/toray-extends-comprehensive-agreement-with-boeing-to-supply-carbon-fiber-torayca-prepreg/", "Source Toray : accord long terme pour fournir du prepreg carbone TORAYCA pour Boeing 777X et 787.", categories="dependance_source_unique", hits="dependance_source_unique:single source", weak=0.18, aero=1.0, official=1),
            result("Toray Composite Materials America and Syensqo long-term agreement", "https://www.toray.us/media-news/article.html?contentId=f1j40nbv", "Source Toray 2026 : accord cinq ans visant la stabilite d'approvisionnement pour aerospace, space et defense.", aero=1.0, official=1),
        ],
    },
    {
        "site_uid": "mitsubishi_chemical@@mitsubishi_chemical@35.6812,139.7671",
        "supplier": "Mitsubishi Chemical",
        "query": "Mitsubishi Chemical carbon fiber aerospace Boeing cabin panels",
        "weak": 0.12,
        "cats": "dependance_source_unique",
        "hits": "dependance_source_unique:single source",
        "doc": 0.20,
        "aero": 0.85,
        "official": 1,
        "confidence": 0.82,
        "summary": "Capacite confirmee : fibres carbone et thermoplastiques pour aerospace ; criticite moderee liee au role matiere composite amont.",
        "results": [
            result("Mitsubishi Chemical Carbon Fiber global supply chain", "https://www.m-chemical.co.jp/carbon-fiber/en/global/", "Source officielle : reseau global de fibre carbone Mitsubishi Chemical.", aero=0.85, official=1),
            result("KyronTEX cabin panels Boeing case study", "https://www.mcam.com/en/case-studies/kyrontex-cabin-panels-boeing", "Source officielle : cas d'usage panneaux cabine Boeing avec thermoplastiques Mitsubishi.", categories="dependance_source_unique", hits="dependance_source_unique:single source", weak=0.12, aero=0.9, official=1),
        ],
    },
    {
        "site_uid": "ets_gattefin_tier1@@ets_gattefin_tier1@47.1426393,2.2372016",
        "supplier": "ETS Gattefin",
        "query": "ETS Gattefin aerospace machining France",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.08,
        "aero": 0.35,
        "official": 1,
        "confidence": 0.70,
        "summary": "Specialite a confirmer : fournisseur industriel francais ; peu de signaux publics exploitables, pas de crise specifique trouvee.",
        "results": [
            result("Gattefin", "https://gattefin.fr/", "Source officielle : fournisseur industriel francais, contexte public limite.", aero=0.35, official=1),
            result("Etablissement Gattefin - Kompass", "https://lb.kompass.com/c/etablissement-gattefin/fr1917783/", "Profil entreprise secondaire utile pour localiser et qualifier l'activite.", aero=0.2),
        ],
    },
    {
        "site_uid": "jamco_aircraft_interiors_-_niigata__tier1@@jamco_aircraft_interiors_-_niigata__tier1@38.0218,139.4275",
        "supplier": "JAMCO Aircraft Interiors - Niigata",
        "query": "Jamco aircraft interiors Niigata factory supplier",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.11,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.88,
        "summary": "Specialite confirmee : fabrication d'interieurs avion a Niigata ; reseau global Jamco, pas de crise specifique trouvee dans cette recherche.",
        "results": [
            result("JAMCO Aircraft Interiors - Niigata Factory", "https://www.jamco.co.jp/en/company/group.html", "Source officielle : Jamco Aircraft Interiors Corporation fabrique des interieurs avion a Murakami/Niigata.", aero=1.0, official=1),
            result("Jamco Interiors", "https://jamcointeriors.com/", "Source officielle : ingenierie, manufacturing et support depuis Japon, Ameriques, Europe et Asie.", aero=1.0, official=1),
        ],
    },
    {
        "site_uid": "saarstahl@@saarstahl@49.3594,7.1715",
        "supplier": "Saarstahl",
        "query": "Saarstahl steel supplier industry risk Europe",
        "weak": 0.18,
        "cats": "risque_geopolitique_reglementaire",
        "hits": "risque_geopolitique_reglementaire:export restrictions",
        "doc": 0.24,
        "aero": 0.25,
        "official": 1,
        "confidence": 0.72,
        "summary": "Contexte matiere : acier europeen, fournisseur industriel ; criticite documentaire moderee par exposition energie/marche acier plus que par crise fournisseur specifique.",
        "results": [
            result("Saarstahl - official company site", "https://en.saarstahl.com/", "Source officielle : producteur acier et fournisseur industriel allemand.", aero=0.25, official=1),
            result("OECD Steel Outlook 2026", "https://www.oecd.org/en/publications/2026/06/oecd-steel-outlook-2026_a79fb861/full-report/international-efforts-to-address-the-steel-crisis-are-intensifying_b6ca4947.html", "Contexte secteur : tensions et politiques non-marchandes sur acier, utile pour stress macro de la matiere.", categories="risque_geopolitique_reglementaire", hits="risque_geopolitique_reglementaire:export restrictions", weak=0.18),
        ],
    },
    {
        "site_uid": "aubert_duval@@aubert_duval@45.7772,3.087",
        "supplier": "Aubert & Duval",
        "query": "Aubert Duval strategic aerospace supplier Airbus Safran acquisition",
        "weak": 0.28,
        "cats": "dependance_source_unique",
        "hits": "dependance_source_unique:single source",
        "doc": 0.34,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.90,
        "summary": "Capacite critique confirmee : fournisseur strategique de pieces et materiaux critiques aerospace/defense, securise par Airbus et Safran.",
        "results": [
            result("Airbus, Safran and Tikehau finalise acquisition of Aubert & Duval", "https://www.airbus.com/en/newsroom/press-releases/2023-04-airbus-safran-and-tikehau-capital-finalise-acquisition-of-aubert", "Source Airbus : acquisition d'Aubert & Duval, fournisseur strategique de pieces et materiaux critiques.", categories="dependance_source_unique", hits="dependance_source_unique:single source", weak=0.28, aero=1.0, official=1),
            result("Airbus and Safran buy Tikehau share in Aubert & Duval", "https://aviationweek.com/aerospace/manufacturing-supply-chain/airbus-safran-buy-tikehaus-share-metal-supplier-aubert-duval", "Article secteur 2026 : Airbus et Safran renforcent la securisation des metaux critiques aerospace.", categories="dependance_source_unique", hits="dependance_source_unique:single source", weak=0.25, aero=0.9),
        ],
    },
    {
        "site_uid": "schroth_safety_products@@schroth_safety_products@26.18,-80.19",
        "supplier": "SCHROTH Safety Products",
        "query": "SCHROTH aerospace restraint systems supplier official",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.10,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.90,
        "summary": "Specialite confirmee : systemes de retenue et ceintures aeronautiques ; pas de crise publique specifique trouvee.",
        "results": [
            result("SCHROTH aerospace restraint systems", "https://www.schroth.com/en/aerospace/general-aviation/t/restraint-systems-3/", "Source officielle : systemes de retenue pour avions, pilotes, equipage et passagers.", aero=1.0, official=1),
            result("SCHROTH secondary barriers for Airbus aircraft", "https://loargroup.com/news/schroth-safety-products-to-supply-installed-physical-secondary-barriers-for-airbus-aircraft/", "Article entreprise : solutions cockpit/cabine et sites en Allemagne et Floride.", aero=1.0),
        ],
    },
    {
        "site_uid": "thales__tier1@@thales__tier1@43.5638842,1.3821146",
        "supplier": "Thales",
        "query": "Thales aerospace electronics cyber aviation supply chain risk",
        "weak": 0.58,
        "cats": "cyber_securite",
        "hits": "cyber_securite:ransomware|cyber_securite:cyberattack",
        "doc": 0.48,
        "aero": 0.90,
        "official": 1,
        "confidence": 0.84,
        "summary": "Signal sectoriel fort : Thales documente une hausse des cyberattaques dans l'aviation ; pour le noeud electronique, cela augmente la vigilance supply numerique.",
        "results": [
            result("Aviation sector sees 600% year-on-year increase in cyberattacks", "https://www.thalesgroup.com/en/news-centre/press-releases/aviation-sector-sees-600-year-year-increase-cyberattacks", "Source Thales : hausse forte des rancongiciels et attaques cyber dans le secteur aviation entre 2024 et 2025.", categories="cyber_securite", hits="cyber_securite:ransomware|cyber_securite:cyberattack", weak=0.58, aero=0.9, official=1),
            result("Thales supplier relations", "https://www.thalesgroup.com/en/supplier-relations", "Source officielle : cadre relations fournisseurs et maitrise des risques tiers.", aero=0.75, official=1),
        ],
    },
    {
        "site_uid": "basf_pu_chemistry_source_candidate_tier4_raw_material@@basf_pu_chemistry_source_candidate_tier4_raw_material@49.481,8.435",
        "supplier": "BASF",
        "query": "BASF polyurethane foam raw materials supplier",
        "weak": 0.10,
        "cats": "risque_geopolitique_reglementaire",
        "hits": "risque_geopolitique_reglementaire:pfas",
        "doc": 0.18,
        "aero": 0.45,
        "official": 1,
        "confidence": 0.74,
        "summary": "Contexte matiere chimique : polyols/isocyanates pour mousses PU ; pertinence siege indirecte, vigilance reglementaire chimie.",
        "results": [
            result("Polyurethane Raw Materials - BASF", "https://chemicals.basf.com/north-america/en/Monomers/isocyanates-and-polyols", "Source officielle : BASF fournit matieres premieres pour mousses flexibles et moulees.", aero=0.45, official=1),
            result("Molded Flexible Foam - BASF", "https://chemicals.basf.com/north-america/en/Monomers/isocyanates-and-polyols/markets/molded-flexible-foam", "Source officielle : mousses polyurethane moulees liees aux systemes de sieges et applications de confort/securite.", aero=0.35, official=1),
        ],
    },
    {
        "site_uid": "franklin_tier1@@franklin_tier1@51.8215327,20.5268712",
        "supplier": "FRANKLIN",
        "query": "Franklin Products aircraft seat cushion upholstery supplier",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.10,
        "aero": 1.0,
        "official": 0,
        "confidence": 0.82,
        "summary": "Specialite confirmee : coussins et habillage de sieges airline ; pas de crise publique specifique trouvee.",
        "results": [
            result("Franklin Products - Aircraft Interiors Expo", "https://www.aircraftinteriorsexpo.com/en-gb/exhibitor-directory/exhibitor-details.franklin%20products.org-67daa48f-972a-478b-b59d-726dcf3001e4.html", "Source salon : Franklin mene le marche des coussins et revetements de sieges airline.", aero=1.0),
            result("Franklin Products - Airline Suppliers", "https://www.airline-suppliers.com/supplier/franklin-products-inc", "Source secteur : innovations esthetiques, ergonomiques et engineering pour coussins/habillage de sieges.", aero=1.0),
        ],
    },
    {
        "site_uid": "te_connectivity_tier1@@te_connectivity_tier1@49.0253,1.1858",
        "supplier": "TE Connectivity",
        "query": "TE Connectivity aerospace connectors supplier official",
        "weak": 0.12,
        "cats": "dependance_source_unique",
        "hits": "dependance_source_unique:single source",
        "doc": 0.20,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.86,
        "summary": "Specialite confirmee : connecteurs et capteurs aerospace ; criticite moderee car electronique qualifiee et substitutions souvent non triviales.",
        "results": [
            result("TE Connectivity - Solutions for Aerospace Technologies", "https://www.te.com/en/industries/aerospace.html", "Source officielle : connecteurs pour commandes de vol, hydrauliques, fly-by-wire et trains d'atterrissage.", categories="dependance_source_unique", hits="dependance_source_unique:single source", weak=0.12, aero=1.0, official=1),
            result("TE Connectivity home", "https://www.te.com/en/home.html", "Source officielle : portefeuille de composants, connecteurs et capteurs pour data/power/signal en aviation et industries critiques.", aero=0.75, official=1),
        ],
    },
    {
        "site_uid": "dupont_de_nemours@@dupont_de_nemours@39.7391,-75.5398",
        "supplier": "DuPont de Nemours",
        "query": "DuPont PFAS environmental settlement aerospace polymer supplier",
        "weak": 0.72,
        "cats": "risque_geopolitique_reglementaire|qualite_conformite",
        "hits": "risque_geopolitique_reglementaire:pfas|qualite_conformite:lawsuit",
        "doc": 0.68,
        "aero": 0.45,
        "official": 1,
        "confidence": 0.82,
        "summary": "Signal reglementaire fort : contentieux PFAS et accord environnemental New Jersey ; a surveiller pour polymers/fibres et conformite fournisseur.",
        "results": [
            result("DuPont/Chemours/Corteva New Jersey PFAS agreement", "https://www.dupont.com/news/chemours-dupont-and-corteva-reach-agreement-with-the-state-of-new-jersey-to-comprehensively-resolve-all-environmental-claims-including-pfas.html", "Source DuPont : accord de reglement de reclamations environnementales incluant PFAS, paiements sur 25 ans a partir de 2026.", categories="risque_geopolitique_reglementaire|qualite_conformite", hits="risque_geopolitique_reglementaire:pfas|qualite_conformite:lawsuit", weak=0.72, aero=0.15, official=1),
            result("NJDEP DuPont settlement", "https://dep.nj.gov/dupont/", "Source autorite publique : remediation, dommages aux ressources naturelles et couts de nettoyage.", categories="risque_geopolitique_reglementaire|qualite_conformite", hits="risque_geopolitique_reglementaire:pfas|qualite_conformite:lawsuit", weak=0.74),
        ],
    },
    {
        "site_uid": "amsafe@@amsafe@33.456,-112.16",
        "supplier": "AmSafe",
        "query": "AmSafe aircraft seatbelts restraint systems supplier official",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.10,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.92,
        "summary": "Specialite confirmee : ceintures, airbags et systemes de retenue aerospace/defense ; pas de crise specifique trouvee.",
        "results": [
            result("AmSafe - Home", "https://www.amsafe.com/", "Source officielle : fournisseur leader de ceintures, retenues et airbags de sieges pour aviation commerciale, militaire et civile.", aero=1.0, official=1),
            result("AmSafe aircraft seatbelt", "https://www.amsafe.com/product/traditional-aircraft-seatbelt/", "Source officielle : produits de ceintures aeronautiques, aerospace and defense.", aero=1.0, official=1),
        ],
    },
    {
        "site_uid": "3m@@3m@41.9519,-88.7122",
        "supplier": "3M",
        "query": "3M PFAS settlement supplier materials risk",
        "weak": 0.66,
        "cats": "risque_geopolitique_reglementaire|qualite_conformite",
        "hits": "risque_geopolitique_reglementaire:pfas|qualite_conformite:lawsuit",
        "doc": 0.62,
        "aero": 0.35,
        "official": 1,
        "confidence": 0.78,
        "summary": "Signal reglementaire fort : contentieux PFAS sur un fournisseur de materiaux industriels divers ; impact potentiel a qualifier selon les familles matieres utilisees.",
        "results": [
            result("3M resolves PFAS-related claims with New Jersey", "https://investors.3m.com/news-events/press-releases/detail/1887/3m-resolves-pfas-related-claims-with-the-state-of-new-jersey", "Source 3M investisseurs : resolution de reclamations PFAS avec l'Etat du New Jersey.", categories="risque_geopolitique_reglementaire|qualite_conformite", hits="risque_geopolitique_reglementaire:pfas|qualite_conformite:lawsuit", weak=0.66, aero=0.1, official=1),
            result("3M PFAS stewardship", "https://www.3m.com/3M/en_US/pfas-stewardship/uses-applications/", "Source 3M : contexte d'usage et de gestion des PFAS dans les applications industrielles.", categories="risque_geopolitique_reglementaire", hits="risque_geopolitique_reglementaire:pfas", weak=0.48, aero=0.15, official=1),
        ],
    },
    {
        "site_uid": "kronotex_gmbh_co@@kronotex_gmbh_co@53.1472,12.3793",
        "supplier": "Kronotex GmbH & Co",
        "query": "Kronotex low formaldehyde panels official",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.08,
        "aero": 0.20,
        "official": 1,
        "confidence": 0.72,
        "summary": "Specialite matiere bois/panneau a confirmer pour le siege ; source officielle positive sur faibles emissions de formaldehyde.",
        "results": [
            result("Kronotex - Swiss Krono", "https://m.kronotex.com/Kronotex-0008163044.html", "Source officielle : emissions de formaldehyde indiquees faibles et comparables au bois non traite.", aero=0.2, official=1),
        ],
    },
    {
        "site_uid": "celso_sas@@celso_sas@43.9363,1.3228",
        "supplier": "Celso SAS",
        "query": "Celso aerospace aviation foam France supplier",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.09,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.90,
        "summary": "Specialite confirmee : transformation de mousses pour sieges avion, famille Airbus et aviation VIP/business.",
        "results": [
            result("Aerospace & Aviation Foam - Celso", "https://celso.fr/en/aerospace-aviation-foam-celso/", "Source officielle : coussins, dossiers, appuie-tetes et mousses pour sieges avion, Airbus et aviation d'affaires.", aero=1.0, official=1),
            result("CELSO technical foams and cellular materials transformer", "https://celso.fr/en/celso-cellular-materials-transformer/", "Source officielle : produits finis et semi-finis pour aerospace, medical et industriel.", aero=0.85, official=1),
        ],
    },
    {
        "site_uid": "glatfelter@@glatfelter@39.8712,-76.864",
        "supplier": "Glatfelter",
        "query": "Glatfelter nonwovens engineered materials acquisition",
        "weak": 0.12,
        "cats": "dependance_source_unique",
        "hits": "dependance_source_unique:single source",
        "doc": 0.16,
        "aero": 0.25,
        "official": 0,
        "confidence": 0.72,
        "summary": "Contexte matiere non-tissee : fournisseur d'engineered materials ; acquisition GP utile pour capacite, criticite faible a moderee faute de lien aerospace direct.",
        "results": [
            result("GP sale of nonwovens business to Glatfelter finalized", "https://news.gp.com/2021/05/gp-announces-sale-of-nonwovens-business-to-glatfelter", "Source Georgia-Pacific : vente d'activites nonwovens a Glatfelter, fournisseur mondial d'engineered materials.", categories="dependance_source_unique", hits="dependance_source_unique:single source", weak=0.12, aero=0.25),
        ],
    },
    {
        "site_uid": "halcyon_hevecam@@halcyon_hevecam@2.9406,9.9102",
        "supplier": "Halcyon Hevecam",
        "query": "Halcyon Hevecam natural rubber Cameroon sustainability risk",
        "weak": 0.54,
        "cats": "risque_geopolitique_reglementaire|qualite_conformite",
        "hits": "risque_geopolitique_reglementaire:forced labor|qualite_conformite:lawsuit",
        "doc": 0.50,
        "aero": 0.20,
        "official": 1,
        "confidence": 0.76,
        "summary": "Signal ESG fort : caoutchouc naturel au Cameroun, deforestation/tracabilite et plans correctifs ; important pour elastomeres et mousses.",
        "results": [
            result("Halcyon Agri natural rubber supply chain plantations", "https://www.halcyonagri.com/en/what-we-do/natural-rubber-supply-chain/plantations/", "Source officielle : plantations et supply chain caoutchouc naturel.", aero=0.2, official=1),
            result("Halcyon Five Years On - Mighty Earth report", "https://mightyearth.org/wp-content/uploads/2024/12/Halcyon-Five-Years-On_December-2024_Mighty-Earth.pdf", "Rapport ONG : suivi des engagements et controverses historiques sur deforestation et impacts sociaux.", categories="risque_geopolitique_reglementaire|qualite_conformite", hits="risque_geopolitique_reglementaire:forced labor|qualite_conformite:lawsuit", weak=0.54),
            result("Halcyon Sustainability Report 2025", "https://links.sgx.com/1.0.0/corporate-announcements/Y9UPT6AZVYJ75YBB/887750_HAC_Sustainability%20Report%202025.pdf", "Rapport 2025 : tracabilite et suspension temporaire d'achats avec plans correctifs fournisseur.", categories="qualite_conformite", hits="qualite_conformite:disruption", weak=0.35, official=1),
        ],
    },
    {
        "site_uid": "sabic@@sabic@24.7136,46.6753",
        "supplier": "SABIC",
        "query": "SABIC LEXAN aircraft interiors polycarbonate supplier",
        "weak": 0.08,
        "cats": "risque_geopolitique_reglementaire",
        "hits": "risque_geopolitique_reglementaire:export restrictions",
        "doc": 0.16,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.88,
        "summary": "Specialite confirmee : solutions LEXAN/thermoplastiques pour interieurs avion ; criticite moderee par dependance matiere chimique globale.",
        "results": [
            result("SABIC aircraft interiors 2022", "https://www.sabic.com/en/newsandmedia/events/event-details/aircraft-interiors-2022", "Source officielle : portefeuille LEXAN polycarbonate pour allegement, conformite reglementaire et interieurs aerospace.", aero=1.0, official=1),
            result("SABIC aircraft cabin interiors", "https://www.sabic.com/en/industries/mass-transportation/aircraft-interiors/aircraft-cabin-interiors", "Source officielle : solutions legeres et conformes pour interieurs cabine du plafond au plancher.", aero=1.0, official=1),
        ],
    },
    {
        "site_uid": "china_baowu_baosteel@@china_baowu_baosteel@31.2304,121.4737",
        "supplier": "China Baowu / Baosteel",
        "query": "China Baowu steel risk negative outlook supply chain",
        "weak": 0.42,
        "cats": "fragilite_financiere|risque_geopolitique_reglementaire",
        "hits": "fragilite_financiere:negative outlook|risque_geopolitique_reglementaire:export restrictions",
        "doc": 0.44,
        "aero": 0.20,
        "official": 0,
        "confidence": 0.72,
        "summary": "Signal macro fort : acier chinois sous pression, notation/outlook et crise sectorielle ; contexte matiere, pas incident site unique.",
        "results": [
            result("Baowu and subsidiaries outlook revised to negative - S&P Global", "https://www.spglobal.com/ratings/en/regulatory/article/-/view/type/HTML/id/3391673", "S&P : perspective negative liee aux conditions faibles de l'industrie acier chinoise et reduction de dette.", categories="fragilite_financiere", hits="fragilite_financiere:negative outlook", weak=0.42),
            result("World biggest steel producer warns of severe industry crisis", "https://gmk.center/en/news/baowu-steel-warns-of-a-serious-crisis-in-the-chinese-steel-industry/", "Article secteur : Baowu signale une crise plus severe et durable dans l'acier chinois.", categories="risque_geopolitique_reglementaire", hits="risque_geopolitique_reglementaire:disruption", weak=0.36),
        ],
    },
    {
        "site_uid": "shandong_loyal_chemical_co_ltd@@shandong_loyal_chemical_co_ltd@36.7059,117.0166",
        "supplier": "Shandong Loyal Chemical Co., Ltd.",
        "query": "Shandong Loyal Chemical polyurethane chemical supplier China",
        "weak": 0.20,
        "cats": "risque_geopolitique_reglementaire",
        "hits": "risque_geopolitique_reglementaire:export restrictions",
        "doc": 0.24,
        "aero": 0.20,
        "official": 0,
        "confidence": 0.55,
        "summary": "Contexte limite : fournisseur chimie Chine, lien aerospace non confirme ; criticite documentaire surtout liee au risque pays/matiere.",
        "results": [
            result("Shandong Loyal Chemical company introduction", "https://www.sdloyalchemical.com/aboutus.html", "Source entreprise : fabricant de silicone glue, lien aerospace non confirme.", aero=0.1),
            result("Supply chain risks to watch for 2026", "https://www.z2data.com/insights/22-critical-supply-chain-risks-to-watch-for-in-2026/", "Contexte supply 2026 : conflits, tarifs et restrictions export comme risques amont generiques.", categories="risque_geopolitique_reglementaire", hits="risque_geopolitique_reglementaire:export restrictions", weak=0.20),
        ],
    },
    {
        "site_uid": "zhejiang_yuxin_textile_co_ltd@@zhejiang_yuxin_textile_co_ltd@30.5278,120.4306",
        "supplier": "Zhejiang Yuxin Textile Co.,Ltd.",
        "query": "Zhejiang Yuxin Textile supplier China supply chain risk",
        "weak": 0.22,
        "cats": "risque_geopolitique_reglementaire",
        "hits": "risque_geopolitique_reglementaire:export restrictions",
        "doc": 0.26,
        "aero": 0.25,
        "official": 0,
        "confidence": 0.55,
        "summary": "Contexte limite : textile Chine, specialite aerospace non confirmee ; vigilance pays, transport et conformite.",
        "results": [
            result("Zhejiang Yuxin Textile Co., Ltd.", "https://www.yuxintextile.com/", "Source entreprise : textiles fonctionnels, outdoor, mode et maison ; lien aerospace non confirme.", aero=0.15),
            result("Supply chain risks to watch for 2026", "https://www.z2data.com/insights/22-critical-supply-chain-risks-to-watch-for-in-2026/", "Contexte supply : conflits, tarifs et restrictions d'export peuvent perturber composants et matieres importees.", categories="risque_geopolitique_reglementaire", hits="risque_geopolitique_reglementaire:export restrictions", weak=0.22),
        ],
    },
    {
        "site_uid": "klabin_s_a@@klabin_s_a@-29.7858,-51.1144",
        "supplier": "Klabin S.A.",
        "query": "Klabin pulp paper packaging Brazil supplier sustainability",
        "weak": 0.16,
        "cats": "risque_geopolitique_reglementaire",
        "hits": "risque_geopolitique_reglementaire:disruption",
        "doc": 0.18,
        "aero": 0.15,
        "official": 1,
        "confidence": 0.62,
        "summary": "Contexte emballage/papier Bresil : lien siege indirect ; criticite faible a moderee par exposition climat/logistique et matiere bio-sourcee.",
        "results": [
            result("Klabin official site", "https://klabin.com.br/en/", "Source officielle : papier, cellulose, emballage, innovation et durabilite.", aero=0.15, official=1),
            result("Klabin sustainable operations", "https://klabin.com.br/en/sustentabilidade/operacao-sustentavel", "Source officielle : operations durables et produits renouvelables/recyclables.", aero=0.1, official=1),
        ],
    },
    {
        "site_uid": "liebherr_aerospace_tier1@@liebherr_aerospace_tier1@47.5963892,9.8653206",
        "supplier": "Liebherr Aerospace",
        "query": "Liebherr Aerospace official aircraft systems supplier",
        "weak": 0.0,
        "cats": "",
        "hits": "",
        "doc": 0.10,
        "aero": 1.0,
        "official": 1,
        "confidence": 0.86,
        "summary": "Specialite confirmee : fournisseur de premier rang de systemes embarques aerospace ; pas de crise specifique trouvee.",
        "results": [
            result("Liebherr-Aerospace & Transportation", "https://www.liebherr.com/en-us/aerospace-and-transportation-systems/liebherr-aerospace-transportation-7173790", "Source officielle : fournisseur de premier rang de solutions embarquees aerospace et transportation.", aero=1.0, official=1),
            result("Aerospace and transportation systems product segment", "https://www.liebherr.com/en-us/group/about-liebherr/company-profile/product-segments/aerospace-and-transportation-systems/aerospace-and-transportation-systems-3781642", "Source officielle : systemes et composants pour fabricants et operateurs d'avions.", aero=1.0, official=1),
        ],
    },
]


def main() -> None:
    sites = {
        row["site_uid"]: row
        for row in csv.DictReader((DATA_DIR / "primary_supply_sites.csv").open(encoding="utf-8"))
    }
    summary_rows: list[dict[str, object]] = []
    result_rows: list[dict[str, object]] = []
    for entry in ENTRIES:
        site = sites.get(str(entry["site_uid"]), {})
        results = list(entry["results"])
        top = results[0] if results else result("", "", "")
        domains = {domain(str(row["url"])) for row in results if row.get("url")}
        summary_rows.append(
            {
                "site_uid": entry["site_uid"],
                "supplier": entry["supplier"],
                "roles": site.get("roles", ""),
                "country_code": site.get("country_code", ""),
                "location": site.get("location", ""),
                "lat": site.get("lat", ""),
                "lon": site.get("lon", ""),
                "query": entry["query"],
                "provider": PROVIDER,
                "context_search_status": "ok",
                "retrieved_at_utc": RETRIEVED_AT_UTC,
                "result_count": len(results),
                "source_count": len(domains),
                "top_title": top["title"],
                "top_url": top["url"],
                "top_domain": domain(str(top["url"])) if top["url"] else "",
                "weak_signal_score": entry["weak"],
                "weak_signal_categories": entry["cats"],
                "weak_signal_hits": entry["hits"],
                "documentary_criticality_score": entry["doc"],
                "aerospace_relevance_score": entry["aero"],
                "official_source_candidate": entry["official"],
                "data_confidence_score": entry["confidence"],
                "context_short_summary": entry["summary"],
            }
        )
        for rank, row in enumerate(results, start=1):
            result_rows.append(
                {
                    "site_uid": entry["site_uid"],
                    "supplier": entry["supplier"],
                    "roles": site.get("roles", ""),
                    "country_code": site.get("country_code", ""),
                    "location": site.get("location", ""),
                    "lat": site.get("lat", ""),
                    "lon": site.get("lon", ""),
                    "query": entry["query"],
                    "provider": PROVIDER,
                    "search_status": "ok",
                    "retrieved_at_utc": RETRIEVED_AT_UTC,
                    "result_rank": rank,
                    "title": row["title"],
                    "url": row["url"],
                    "domain": domain(str(row["url"])) if row["url"] else "",
                    "description": row["description"],
                    "signal_categories": row["signal_categories"],
                    "signal_hits": row["signal_hits"],
                    "weak_signal_score": row["weak_signal_score"],
                    "aerospace_relevance_score": row["aerospace_relevance_score"],
                    "official_source_candidate": row["official_source_candidate"],
                }
            )

    for path, fields, rows in [
        (DATA_DIR / "supplier_context_summary.csv", SUMMARY_FIELDS, summary_rows),
        (DATA_DIR / "supplier_context_results.csv", RESULT_FIELDS, result_rows),
    ]:
        with path.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
            writer.writeheader()
            writer.writerows(rows)
    print(f"wrote {len(summary_rows)} summary rows and {len(result_rows)} result rows")


if __name__ == "__main__":
    main()
